### ISSUE TITLE
'dispatch()' vs 'dispatch.invoke()'

### ISSUE THREAD

**Issue by pablodeafsapps** [ReKotlin/ReKotlin#18]
Straight to the point, as the title says. I've seen a bunch of examples using the first form in _Activity_/_Fragment_ instances, and the latter in _Middleware_ objects. Is there any difference between them? When shall I use each? Regards!

**Comment by jitinsharma** [comment]
`dispatch` is a kotlin higher order function.
Higher order function can be called directly with it's name like `dispatch()` or using `dispatch.invoke()`
`invoke()` is provided by kotlin and not related to this library.
https://kotlinlang.org/docs/reference/lambdas.html#invoking-a-function-type-instance
