### ISSUE TITLE
Middleware dispatches new action before old one updates state

### ISSUE THREAD

**Issue by andreihava-okta** [ReKotlin/ReKotlin#19]
I have an issue where the state is updated out of order of the dispatched actions.

In the flow outlined below, I would expect it to be called in the outlined order, with the end state being:
```
isFetching: False
isCompleted: True
lastAction: AuthExists
```

Due to some out-of-sync execution of stuff, the middleware gets called first, then the reducer, and the `AuthCheck` action overwrites the already-written `AuthExists` action, with an end result of such:
```
isFetching: True
isCompleted: True
lastAction: AuthCheck
```

Basically, instead of the flow getting executed as outlined below, it executes as: 1, 3, 4, 5, 2.

1. Dispatch `AuthCheck` action on Activity `onCreate`
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_auth)

    [...]

    mainStore.subscribe(this) {
        it.select {
            it.userState
        }.skipRepeats { oldState, newState ->
            oldState == newState
        }
    }

    mainStore.dispatch(AuthCheck(null))
}
```

2. `userReducer` updates state
```kotlin
fun userReducer(action: Action, state: UserState?) : UserState {
    val newState = state ?: UserState(AuthState.NotAuthed, "", "", "", "")

    when (action) {
        is AuthCheck -> {
            return newState.copy(isFetching = true, lastAction = action)
        }

        [...]
    }
    return newState
}
```

3. `authMiddleware` calls `checkUser(action, dispatch)`
```kotlin
internal val authMiddleware: Middleware<AppState?> = { dispatch, _ ->
    { next ->
        { action ->
            when (action) {
                is AuthCheck -> {
                    checkUser(action, dispatch)
                }

                [...]

            }
            next(action)
        }
    }
}
```

4. `checkUser` verifies for an existing user in Firebase, dispatching `AuthExists`
```kotlin
private fun checkUser(action: AuthCheck, dispatch: DispatchFunction) {
    val auth = FirebaseAuth.getInstance()
    val user = auth.currentUser

    if (user != null) {
        dispatch(AuthExists(user.displayName!!, user.email!!, user.uid))
    } else {
        dispatch(AuthNotExists(null))
    }
}
```

5. `userReducer` updates state
```kotlin
fun userReducer(action: Action, state: UserState?) : UserState {
    val newState = state ?: UserState(AuthState.NotAuthed, "", "", "", "")

    when (action) {
        
        [...]

        is AuthExists -> {
            return newState.copy(authState = AuthState.Authed, uId = action.uId, email = action.email,
                    name = action.name, isFetching = false, isCompleted = true, lastAction = action)
        }

        [...]

    }

    return newState
}
```

Can you please assist me on this one?

**Comment by kmmraj** [comment]
@andreihava-okta  - Please refer to the [link](https://github.com/LambdaSchool/Redux-Counter)  -  should clarify the flow. Middleware and the reducers will be called almost simulatenously, not sure you can sequence the calls one after another.
Rather you should drive the state transformation accordingly so that one action should not overwrite another.

**Comment by kaustavjaiswal** [comment]
Closing this issue as there is no response from user - @andreihava-okta

Feel free to reopen this issue or another one for any other clarifications.
