### ISSUE TITLE
view by lazy

### ISSUE THREAD

**Issue by Miha-x64** [ReKotlin/ReKotlin#20]
Hello. This
```
    private val counterLabel: TextView by lazy {
        this.findViewById(R.id.counter_label) as TextView
    }

    private val buttonUp: Button by lazy {
        this.findViewById(R.id.button) as Button
    }

    private val buttonDown: Button by lazy {
        this.findViewById(R.id.button2) as Button
    }
```
produces three anonymous classes for lambdas and three synthetic classes for properties in the bytecode, and creates three synchronized lazies.
Consider using [Kotlin Android Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html) instead.

**Comment by kmmraj** [comment]
Super, @Miha-x64  feel free to create a PR.
