### ISSUE TITLE
Reducer not being invoked

### ISSUE THREAD

**Issue by peterent** [ReKotlin/ReKotlin#41]
I have in MainApplication.kt (this extends Application()) the definition of the store (I'm following the ReduxMovieExample):

```
val store = Store(
    reducer = ::appReducer,
    state = null,
    middleware = listOf(databaseMiddleware)
)
```
The appReducer is never invoked. It is defined in AppReducer.kt as:
```
fun appReducer(action: Action, appState: AppState?) =
    AppState(
        passwordState = passwordReducer(action, appState?.passwordState)
    )
```
My `passwordReducer` is not being called when I dispatch an action. 
My `databaseMiddleware` is being called to handle an action dispatched to it.

*UPDATE*: I have looked at the source code to ReKotlin, specifically `Store.kt`. I am using
```
store.dispatch(AddPassword(password))
```
where `AddPassword` is an `Action` and is supposed to be handled by my `passwordReducer` function.

In `Store.kt`, the function: `override fun dispatch(action:Action)` invokes `this.dispatchFunction(action)`. As near as I can tell, `dispatchFunction` goes through the `middleware` list *ONLY* and never looks at the reducer. So if your middleware isn't handling the action, your reducer will never get it. Maybe I'm just used to Redux in React-Native, but this seems wrong to me. Or is there a different `dispatch` to use?

**Comment by peterent** [comment]
I'm pretty sure this piece of code is not working correctly:
```
override var dispatchFunction: DispatchFunction = middleware
        .reversed()
        .fold({ action: Action -> this._defaultDispatch(action) }, { dispatchFunction, middleware ->
            val dispatch = { action: Action -> this.dispatch(action) }
            val getState = { this._state }
            middleware(dispatch, getState)(dispatchFunction)
        })
```
My knowledge of Kotlin is pretty new, but it looks like the `initial` component of the `fold` is not being executed for some reason.

**Comment by kmmraj** [comment]
The reducer will be invoked, for sure, please refer to the test classes - https://github.com/ReKotlin/ReKotlin/blob/master/src/test/kotlin/org/rekotlin/StoreSubscriberTests.kt .

Just looking at your code supplied in the issue, is your state will remain null, please check that.

**Comment by peterent** [comment]
Thank you for suggesting I look at my code. As I'm trying to learn how to use ReKotlin (I'm reasonably familiar with Redux having working on a React-Native app), I forget to do `next(action)` in my middleware. 

Case closed!
