### ISSUE TITLE
Gradle conflict

### ISSUE THREAD

**Issue by MarisaLopes** [ReKotlin/ReKotlin#9]
should this library be working when we use dagger injection?
I am not able to build the project now.

Got this:
Error:Exception in thread "main" java.lang.NullPointerException: Couldn't find outer class org/rekotlinrouter/Router$routingSerailActionHandler$1$3 of org/rekotlinrouter/Router$routingSerailActionHandler$1$3$1
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1079)
	at com.google.devtools.build.android.desugar.ClassVsInterface.isOuterInterface(ClassVsInterface.java:56)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitOuterClass(InterfaceDesugaring.java:246)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:638)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForSmartboxStaging'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/20.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/22.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/44.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/46.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/19.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/21.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/38.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/40.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/5.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/7.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/54.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/56.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/32.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/34.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/3.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/5.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/37.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/39.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/8.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/10.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/51.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/53.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/60.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/62.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/6.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/8.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/18.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/20.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/42.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/44.jar --input /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/16.jar --output /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/desugar/smartbox/staging/18.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/classes/smartbox/staging --classpath_entry /Users/marisalopes/beneficiary-app/app/build/tmp/kotlin-classes/smartboxStaging --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/0.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/1.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/2.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/3.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/4.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/5.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/6.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/7.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/8.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/9.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/10.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/11.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/12.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/13.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/14.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/15.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/16.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/17.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/18.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/19.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/20.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/21.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/22.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/23.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/24.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/25.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/26.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/27.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/28.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/29.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/30.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/31.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/32.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/33.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/34.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/35.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/36.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/37.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/38.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/39.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/40.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/41.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/42.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/43.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/44.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/45.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/46.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/47.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/48.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/49.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/50.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/51.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/52.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/53.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/54.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/55.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/56.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/57.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/58.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/59.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/60.jar --classpath_entry /Users/marisalopes/beneficiary-app/app/build/intermediates/transforms/stackFramesFixer/smartbox/staging/61.jar --bootclasspath_entry /Users/marisalopes/Library/Android/sdk/platforms/android-27/android.jar --bootclasspath_entry /Users/marisalopes/Library/Android/sdk/platforms/android-27/optional/org.apache.http.legacy.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/resources.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/rt.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/jsse.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/jce.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/charsets.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes --legacy_jacoco_fix}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by kmmraj** [comment]
Could you please share you gradle files

**Comment by kmmraj** [comment]
@Binghammer - Can you please share the gradle files?

**Comment by kaustavjaiswal** [comment]
Closing this issue as there is no update from the user - @Binghammer 

Feel free to reopen this or create a new issue if this problem still occurs.
